version: 2

jobs:
    python-3.6: &test-template
        docker:
            - image: circleci/python:3.6-stretch-node-browsers
              auth:
                username: dashautomation
                password: $DASH_PAT_DOCKERHUB

        environment:
            PERCY_ENABLE: 0

        steps:
            - checkout

            - run:
                name: ✍️ Write job name.
                command: echo $CIRCLE_JOB > circlejob.txt

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

            - run:
                name: 🏗️ Create virtualenv
                command: |
                    sudo pip install virtualenv
                    python -m venv venv || virtualenv venv

            - run:
                name: 🏗️ Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - venv

            - run:
                name: 🧪 Generations tests
                command: |
                    . venv/bin/activate
                    pytest
                when: always

    python-3.7-install-test:
        docker:
            - image: circleci/python:3.7-stretch-node-browsers
              auth:
                username: dashautomation
                password: $DASH_PAT_DOCKERHUB

        environment:
            PERCY_ENABLE: 0

        steps:
            - checkout

            - run:
                name: ✍️ Write job name.
                command: echo $CIRCLE_JOB > circlejob.txt

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

            - run:
                name: 🏗️ Create virtualenv
                command: |
                    sudo pip install virtualenv
                    python -m venv venv || virtualenv venv

            - run:
                name: 🏗️ Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - venv

            - run:
                name: 🧪 Generate Project & test
                command: |
                    . venv/bin/activate
                    mkdir test_install
                    cd test_install
                    cookiecutter .. --config-file ../tests/test_config.yaml --no-input
                    cd test_component
                    python -m venv venv
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet
                    npm install --ignore-scripts
                    npm run build
                    pytest


workflows:
    version: 2
    build:
        jobs:
            - python-3.6:
                context: dash-docker-hub
            - python-3.7-install-test:
                context: dash-docker-hub
